language: php

php: [7.2, 7.3, 7.4]

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --optimize-autoloader

script:
  - composer ci